#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Audited Android 16 / gold OS3 202404 CIL compatibility corrections.

Applied to fresh image staging after source compilation, never to installed
policy. Keep every neverallow expression; repair stale attribute membership
and remove invalid or inapplicable grants. Unknown inputs fail closed.
"""
import re


def require(condition, message):
    if not condition:
        raise ValueError(message)


def replace_once(text, old, new):
    require(text.count(old) == 1, 'Expected one audited policy statement: ' + old[:100])
    return text.replace(old, new)


def preserve_assertions(before, after):
    # CIL generated by checkpolicy contains one statement per line.
    assertions = lambda text: [line for line in text.splitlines()
                               if line.lstrip().startswith(('(neverallow ', '(neverallowx '))]
    require(assertions(before) == assertions(after), 'A neverallow assertion changed')
    return after


def public_attributes(text):
    """vendor_vm_data_file labels /data, not the read-only /vendor image."""
    lines = text.splitlines(keepends=True)
    matches = [i for i, line in enumerate(lines)
               if line.startswith('(typeattributeset vendor_file_type ')]
    require(len(matches) == 1, 'Expected one vendor_file_type contribution')
    i = matches[0]
    lines[i] = replace_once(lines[i], 'vendor_vm_data_file_202404 ', '')
    return preserve_assertions(text, ''.join(lines))


BINDER_SERVICE_LABELS = (
    'mtk_safe_service_manager_type', 'goodix_fingerprint_vndservice',
    'hal_health_storage_hwservice_202404',
)


def vendor_policy(text):
    fixed = public_attributes(text)
    kept, invalid_binder, obsolete = [], [], []
    for line in fixed.splitlines(keepends=True):
        # Binder operates between process domains. These service-manager object
        # labels can never identify a Binder peer; retain real find/call rules.
        if (line.startswith('(allow ') and '(binder (' in line
                and any(' ' + label + ' ' in line for label in BINDER_SERVICE_LABELS)):
            invalid_binder.append(line)
        elif line == '(allow system_server_202404 self (capability (sys_module)))\n':
            obsolete.append(line)
        elif re.fullmatch(
                r'\(allow (cittest_app|cqrtest_app|system_app_202404) '
                r'vendor_persist_camera_prop \(property_service \(set\)\)\)\n', line):
            # Lineage treats this allow/excludelist as init-owned configuration.
            # Keep app reads and init/vendor_init setters, not OEM runtime writes.
            obsolete.append(line)
        else:
            kept.append(line)
    require(len(invalid_binder) == 8, 'Unexpected ill-typed Binder rule set')
    require(len(obsolete) == 4, 'Unexpected obsolete capability/property rule set')
    return preserve_assertions(text, ''.join(kept))


def mapping_policy(text):
    fixed = text
    for name in ('face', 'fingerprint'):
        # Android split system virtual-HAL properties from their old vendor
        # labels. Do not import the old vendor ownership onto the new types.
        old = (f'(typeattributeset virtual_{name}_hal_prop_202404 '
               f'(virtual_{name}_hal_prop virtual_{name}_prop))')
        new = (f'(typeattributeset virtual_{name}_hal_prop_202404 '
               f'(virtual_{name}_hal_prop))')
        fixed = replace_once(fixed, old, new)
    return preserve_assertions(text, fixed)


def platform_policy(text):
    fixed = text
    for domain in ('hal_audio_server', 'hal_codec2_server'):
        # Debug TCP FDs from su conflict with stock HAL network isolation.
        fixed = replace_once(fixed,
            f'(allow {domain} su (tcp_socket (read write accept getopt)))\n', '')
    for prop in ('apexd_select_prop', 'media_variant_prop'):
        # gold does not ship init_dev_config. The image builder verifies this
        # before dropping its unused writes; init/vendor_init remain owners.
        fixed = replace_once(fixed,
            f'(allow init_dev_config {prop} (property_service (set)))\n', '')
    targets = re.findall(r'\(allow llkd (base_typeattr_\d+) \(process \(ptrace\)\)\)', fixed)
    require(len(targets) == 1, 'Unexpected llkd debug ptrace policy')
    target = targets[0]
    require('gold_llkd_ptrace_domain' not in fixed, 'Policy is already migrated')
    fixed = replace_once(fixed, f'(allow llkd {target} (process (ptrace)))',
        '(typeattribute gold_llkd_ptrace_domain)\n'
        f'(typeattributeset gold_llkd_ptrace_domain (and ({target}) (not (appdomain))))\n'
        '(allow llkd gold_llkd_ptrace_domain (process (ptrace)))')
    # No permissive domains in the new image, including the userdebug su domain.
    fixed = replace_once(fixed, '(typepermissive su)\n', '')
    return preserve_assertions(text, fixed)


def system_ext_policy(text):
    fixed = text
    for domain in ('osi', 'backuptool'):
        fixed = replace_once(fixed, f'(typepermissive {domain})\n', '')
    return preserve_assertions(text, fixed)


def require_absent_helper(root):
    require(not list(root.rglob('*init_dev_config*')),
            'init_dev_config exists; its property-write requirements need review')
    for path in root.rglob('*.rc'):
        if path.is_file():
            require('init_dev_config' not in path.read_text(errors='replace'),
                    'init_dev_config has an init service; do not prune its grants')
